version: 1.0.{build}
skip_tags: true
image: Visual Studio 2022
init:
  - git config --global core.autocrlf true
environment:
  access_token:
    secure: Eq6BjtZ80BXKLwFMg76IjuQAvbLjbojIF/X/ARouGVhxPneJtgDfCXMPNgJ7KBKq
  sonar_token:
    secure: W7pHKhuTW6Lh8WlXJNTOIaOzeuxLi+H6Nqmnm4pr28jM6jyIpOZ+1r10lIQi0eCA
  JAVA_HOME: C:\Program Files\Java\jdk19
nuget:
  disable_publish_on_pr: true
build_script:
  - dotnet --info
  - dotnet restore
  - dotnet build -c Release
  - dotnet pack --include-symbols --include-source -c Release FileWatcher
  - dotnet pack --include-symbols --include-source -c Release FileWatcher.Service
  - dotnet publish -r win-x64 --sc=false -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:IncludeNativeLibrariesForSelfExtract=true -c Release FileWatcher.Service
  - echo {"Tasks":[]} > config.json
  - 7z a -mx=9 FileWatcher.%APPVEYOR_BUILD_VERSION%.win-x64.exe.zip ".\FileWatcher.Service\bin\Release\net6.0\win-x64\publish\FileWatcher.Service.exe" config.json
test_script:
  - ps: |
      if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"mganss_FileWatcher" /v:$env:APPVEYOR_BUILD_VERSION /o:"mganss-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.token="$env:sonar_token" /d:sonar.cs.opencover.reportsPaths="$($env:APPVEYOR_BUILD_FOLDER)\coverage.xml" /d:sonar.coverage.exclusions="FileWatcher.Service/*.cs,FileWatcher.TestCommand/*.cs" /n:FileWatcher
          dotnet build
      }
  - dotnet test /p:CollectCoverage=true FileWatcher.Test\FileWatcher.Test.csproj
  - ps: cp coverage.*.xml ./coverage.xml
  - ps: |
      if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
          dotnet sonarscanner end /d:sonar.token="$env:sonar_token"
      }
  - pip install codecov
  - codecov -f "coverage.xml"
artifacts:
  - path: 'FileWatcher\**\*.*nupkg'
  - path: 'FileWatcher.Service\**\*.*nupkg'
  - path: 'FileWatcher.*.zip'
deploy:
  - provider: GitHub
    tag: v$(APPVEYOR_BUILD_VERSION)
    release: $(APPVEYOR_BUILD_VERSION)
    description: '$(APPVEYOR_REPO_COMMIT_MESSAGE)'
    auth_token:
      secure: Eq6BjtZ80BXKLwFMg76IjuQAvbLjbojIF/X/ARouGVhxPneJtgDfCXMPNgJ7KBKq
    artifact: /FileWatcher\..*\.zip/
    draft: true
    on:
      branch: master
